[profile.default]
src = 'contracts'
out = 'out'
libs = ["lib"] 
test = 'test'
cache_path  = 'cache_forge'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "out" }]
optimize = true
optimizer_runs = 200
solc = "0.8.26"
evm_version = "cancun"
force = true  # Add this line
via-ir = true

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/', 
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/test-devtools-evm-foundry/=lib/devtools/packages/test-devtools-evm-foundry',
    '@layerzero-v2/lz-evm-oapp-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp/',

    # djglsg
]

[rpc_endpoints]
  amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
  polygon = { key = "${POLYGON_SCAN_KEY}" }

[profile.test]
optimize = true
optimizer_runs = 200

[profile.proptest]
cases = 1000
max_shrink_iters = 0  # Set to 0 for unlimited shrinking iterations

[invariant]
runs = 4294967295
depth = 25
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
